server:
  port: 10010
spring:
  application:
    name: zuul-demo

zuul:
  routes:
    user-service: #这里是路由id可以随意写
      path: /user-service/** #这里是映射路径
      url: http://localhost:8081 #映射路径对应的实际url



