logging:
  level:
    com.study: debug
server:
  port: 8081
spring:
  datasource:
#    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/mybatis01
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
  thymeleaf:
    cache: false
  application:
    name: user-service
mybatis:
  type-aliases-package: com.study.pojo
  configuration:
    map-underscore-to-camel-case: true

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10088/eureka

#my:
#  datasource:
#    url: jdbc:mysql://localhost:3306/mybatis01
#    driver-class-name: com.mysql.jdbc.Driver
#    username: root
#    password: root





